### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by tianxiaogu** [gsantner/markor#104]
#### General information

* **Device:**   Android Emulator and Nexus 5
* **Android Version:**  Android 6.0.1
* **App version:**  v0.1.5 (6) from FDroid

```
[APE] // CRASH: net.gsantner.markor (pid 4041) (elapsed nanos: 1890761323424)
[APE] // Short Msg: java.lang.NullPointerException
[APE] // Long Msg: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getParent()' on a null object reference
[APE] // Build Label: Android/sdk_google_phone_x86/generic_x86:6.0/MASTER/4088240:userdebug/test-keys
[APE] // Build Changelist: 4088240
[APE] // Build Time: 1497047463000
[APE] // java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getParent()' on a null object reference
[APE] // 	at net.gsantner.markor.activity.NoteActivity.saveNote(NoteActivity.java:315)
[APE] // 	at net.gsantner.markor.activity.NoteActivity.previewNote(NoteActivity.java:274)
[APE] // 	at net.gsantner.markor.activity.NoteActivity.onOptionsItemSelected(NoteActivity.java:189)
[APE] // 	at android.app.Activity.onMenuItemSelected(Activity.java:2908)
[APE] // 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:368)
[APE] // 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
[APE] // 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
[APE] // 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
[APE] // 	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
[APE] // 	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:202)
[APE] // 	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
[APE] // 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
[APE] // 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
[APE] // 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
[APE] // 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
[APE] // 	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
[APE] // 	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
[APE] // 	at android.view.View.performClick(View.java:5198)
[APE] // 	at android.view.View$PerformClick.run(View.java:21147)
[APE] // 	at android.os.Handler.handleCallback(Handler.java:739)
[APE] // 	at android.os.Handler.dispatchMessage(Handler.java:95)
[APE] // 	at android.os.Looper.loop(Looper.java:148)
[APE] // 	at android.app.ActivityThread.main(ActivityThread.java:5417)
[APE] // 	at java.lang.reflect.Method.invoke(Native Method)
[APE] // 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[APE] // 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[APE] //
```
#### Steps to reproduce

1. Click `new` button
2. Do not input title and click `preview`
3. Click `edit`
4. Input a random title
4. Click `preview`

A sequence of screenshots can be found following these instructions.
Following instructions at 

1. Open <http://wish.cs.ucdavis.edu/sata/sata-net.gsantner.markor-ape-sata-running-time-30/vis-timeline.html>
2. Click `Start` button to adjust the view.
3. Type `348` and click `Select`, click the highlighted event in the timeline. You will see a picture of the screenshot below.
    * The reproduce steps start at 348 and end at 351
    * Use `Move Right` or drag the timeline to move right.

#### Expected result
**What is the expected output?** 

**What do you see instead?**

**Comment by gsantner** [comment]
fixed in 0.1.6 (released)
