### ISSUE TITLE
Repeated crashes when editing a large markdown file

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1128]
I am seeing repeated crashes when editing a relatively large markdown file (~1600 lines, ~12000 words, ~60000 characters.).

I see the following trace. But I am unsure what / where the underlying cause is

```
E/View: hasTransientState decremented below 0: unmatched pair of setHasTransientState calls
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 93208)
E/AccessibilityManager: Error during sending EventType: TYPE_VIEW_TEXT_SELECTION_CHANGED; EventTime: 434232397; PackageName: net.gsantner.markor_test; MovementGranularity: 0; Action: 0; ContentChangeTypes: []; WindowChangeTypes: [] [ ClassName: android.widget.EditText; Text: 
< ENTIRE CONTENTS OF THE DOCUMENT>
ContentDescription: null; ItemCount: 61944; CurrentItemIndex: -1; Enabled: true; Password: false; Checked: false; FullScreen: false; Scrollable: false; BeforeText: null; FromIndex: 61835; ToIndex: 61835; ScrollX: 0; ScrollY: 0; MaxScrollX: 0; MaxScrollY: 0; ScrollDeltaX: -1; ScrollDeltaY: -1; AddedCount: -1; RemovedCount: -1; ParcelableData: null ]; recordCount: 0 
    android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:540)
        at android.view.accessibility.IAccessibilityManager$Stub$Proxy.sendAccessibilityEvent(IAccessibilityManager.java:580)
        at android.view.accessibility.AccessibilityManager.sendAccessibilityEvent(AccessibilityManager.java:606)
        at android.view.ViewRootImpl.requestSendAccessibilityEvent(ViewRootImpl.java:8618)
        at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:1094)
        at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:1094)
        at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:1094)
        at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:1094)
        at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:1094)
E/AccessibilityManager:     at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:1094)
        at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:1094)
        at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:1094)
        at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:1094)
        at android.view.View.requestParentSendAccessibilityEvent(View.java:8333)
        at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:8326)
        at android.view.View.sendAccessibilityEventUnchecked(View.java:8297)
        at android.widget.TextView.sendAccessibilityEventUnchecked(TextView.java:12217)
        at android.view.View.sendAccessibilityEventInternal(View.java:8274)
        at android.widget.TextView.sendAccessibilityEventInternal(TextView.java:12206)
        at android.view.View.sendAccessibilityEvent(View.java:8238)
        at android.widget.TextView.onSelectionChanged(TextView.java:10488)
        at net.gsantner.markor.ui.hleditor.HighlightingEditor.onSelectionChanged(HighlightingEditor.java:279)
        at android.widget.TextView.spanChange(TextView.java:10744)
        at android.widget.TextView$ChangeWatcher.onSpanChanged(TextView.java:13593)
        at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1307)
        at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:651)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:580)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:37)
        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:861)
        at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:197)
        at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:177)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:345)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 93340)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.gsantner.markor_test, PID: 6911
    DeadSystemException: The system died; earlier logs will point to the root cause
I/Process: Sending signal. PID: 6911 SIG: 9
```

**Comment by harshad1** [comment]
Sometimes all I get is 
```
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 92920)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.gsantner.markor_test, PID: 17327
    DeadSystemException: The system died; earlier logs will point to the root cause
```

**Comment by gsantner** [comment]
that a !HUGE! file may not be loadable is known, it's due memory overflow either because reading the file, or the store in android internal textview.

that one however sounds more like on activity change/recreate, is it on quicknote/todo? or e.g. on device rotate?  when do you get the msg

**Comment by harshad1** [comment]
I see the error when I am typing / entering text near the end of the file.

I haven't been able to consistently reproduce it but it does happen multiple times a day.

Nov. 18, 2020 09:11:12 Gregor Santner <notifications@github.com>:

**Comment by gsantner** [comment]
hm, may be a memory issue then with syntax highlighter.. can you disable it for some days and see if it still happens?

**Comment by harshad1** [comment]
Will report back

**Comment by harshad1** [comment]
I think this is solved by https://github.com/gsantner/markor/pull/1130

**Comment by gsantner** [comment]
--> Said 1130 PR is replaced by #1129
