### ISSUE TITLE
Zim Wiki: File generator support for Android < 7 / Java 6

### ISSUE THREAD

**Issue by oddleaf** [gsantner/markor#1194]
#### General information

* **App version: 2.5.0 Google Play** 
* **System: 6.0.1, Samsung J2 Prime (SM-G532G/DS)** 

#### Description

Trying to create a new file with these parameters caused Markor to crash while working on both SD Card and internal storage, with no file was created:

- "Template" set to "zim-wiki-empty.txt" regardless value of "Type"

<br />

Creating a new file with these parameters didn't trigger crash (done as expected on both storages):

- "Template" set to "zim-wiki-reference.txt" regardless value of "Type"
- Any combination of "Type" and "Template" other than "zim-wiki-empty.txt"

<br />

#### Log

```
java.lang.IllegalArgumentException: Unknown pattern character 'X'
	at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
	at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
	at net.gsantner.markor.format.zimwiki.ZimWikiTextActions.createZimWikiHeaderAndTitleContents(ZimWikiTextActions.java:256)
	at net.gsantner.markor.ui.NewFileDialog.getTemplateContent(NewFileDialog.java:272)
	at net.gsantner.markor.ui.NewFileDialog.lambda$makeDialog$5$NewFileDialog(NewFileDialog.java:173)
	at net.gsantner.markor.ui.-$$Lambda$NewFileDialog$t3PMHk03JJI7YTx7crMP_YDKaYs.onClick(lambda)
	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7406)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

<br />

I get it by applying try-catch on `net.gsantner.markor.ui.NewFileDialog` line 171:

```
final byte[] templateContents = getTemplateContent(templateSpinner, basedir, f.getName(), encryptCheckbox.isChecked());
```

**Comment by gsantner** [comment]
Hm I cannot reproduce the issue, the "X" is for timezone and is supposed to be fine.
https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html#iso8601timezone

**Comment by oddleaf** [comment]
Seems to be 'X' is available only from Nougat+ (my device was Marshmallow).

Please refer this: https://stackoverflow.com/questions/44588429/unknown-pattern-character-x-when-using-simpledateformat/46855974#46855974

There's also another answer that states about 'Z', it may could be an alternative...

**Comment by oddleaf** [comment]
Tried your test build, it works smoothly!

Thank you for the great app! It helps me a lot.
