### ISSUE TITLE
App crashes when renaming a '.md' file to a '.txt'

### ISSUE THREAD

**Issue by phunkular** [gsantner/markor#147]
#### General information

* **App version:** 0.2.3 f-droid
* **System:** MIUI 9 / Android 6.0.1

#### Description

Markor crashes when renaming a .md file to a .txt file within the app. The app doesn't crash when changing a file extension from .txt to .md however.

#### Log

I don't have ADB, but this is what MIUI has to say:

java.lang.IllegalStateException: Fragment FilesystemListFragment{561fcc1} not attached to Activity
	at android.support.v4.app.Fragment.getResources(Fragment.java:608)
	at android.support.v4.app.Fragment.getString(Fragment.java:632)
	at net.gsantner.markor.activity.FilesystemListFragment$1.getSectionTitleForItem(FilesystemListFragment.java:96)
	at net.gsantner.markor.activity.FilesystemListFragment$1.getSectionTitleForItem(FilesystemListFragment.java:92)
	at com.mobsandgeeks.adapters.SimpleSectionAdapter.findSections(SimpleSectionAdapter.java:205)
	at com.mobsandgeeks.adapters.SimpleSectionAdapter.notifyDataSetChanged(SimpleSectionAdapter.java:172)
	at net.gsantner.markor.activity.FilesystemListFragment.clearSearchFilter(FilesystemListFragment.java:451)
	at net.gsantner.markor.activity.FilesystemListFragment.broadcastDirectoryChange(FilesystemListFragment.java:325)
	at net.gsantner.markor.activity.FilesystemListFragment.listFilesInDirectory(FilesystemListFragment.java:318)
	at net.gsantner.markor.activity.FilesystemListFragment$2.onReceive(FilesystemListFragment.java:172)
	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:311)
	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:47)
	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:120)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5571)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

**Comment by gsantner** [comment]
Fixed on v0.2.4
