### ISSUE TITLE
Moving a file crashes the app

### ISSUE THREAD

**Issue by tnekent** [gsantner/markor#1545]
## General information
* App version: 2.8.4
* Android version: 11
* Device: Xiaomi Redmi Note 10 Pro
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description
Attempting to move a file often causes the app to crash. There are some instances it doesn't though, and I cannot find a pattern as to when it crashes or not. It crashes just after I press the button to move. I've already searched for similar issues with this but the latest version still crashes for me.

**Comment by harshad1** [comment]
Does copy cause the same issue?

If you are able to find a reproducible series of steps, please do post here.

**Comment by gsantner** [comment]
Cannot reproduce, if somebody else has the issue too or has feedback/stacktrace, please comment here.

**Comment by quadrilo44** [comment]
I get this about 80% of the time I try to move a file, I can't see any pattern to it.

Here's a log I got using Scoop:

```FATAL EXCEPTION: main
Process: net.gsantner.markor, PID: 18298
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getName()' on a null object reference
	at net.gsantner.opoc.ui.FilesystemViewerFragment$1.onFsViewerDoUiUpdate(FilesystemViewerFragment.java:627)
	at net.gsantner.opoc.ui.FilesystemViewerDialog.onFsViewerDoUiUpdate(FilesystemViewerDialog.java:252)
	at net.gsantner.opoc.ui.FilesystemViewerDialog.onViewCreated(FilesystemViewerDialog.java:164)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6165)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by quadrilo44** [comment]
I found out there is a new version (F-Droid wasn't showing it to me: https://github.com/gsantner/markor/issues/1999) so I have installed v2.10.7 and the error doesn't appear anymore.
