### ISSUE TITLE
[jolla] Markor v2.10.2 crashes on Android 4.4

### ISSUE THREAD

**Issue by ntninja** [gsantner/markor#1813]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

It crashes on startup

### Steps to reproduce

1. Update the app in F-Droid
2. Launch it

### Information

Android version: 4.4 (AlienDalvik)
OS version: SailfishOS 4.4
Device: Sony Xperia X
App Version: 2.10.2 (only)

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
W/dalvikvm(26347): VFY: unable to resolve static method 65325:
Lother/writeily/model/WrMarkorSingleton;.getInstance ()Lother/w
riteily/model/WrMarkorSingleton;
D/dalvikvm(26347): VFY: replacing opcode 0x71 at 0x0000
E/dalvikvm(26347): Could not find class 'other.writeily.ui.WrCo
nfirmDialog$ConfirmDialogCallback[]', referenced from method ne
t.gsantner.opoc.ui.FilesystemViewerFragment.askForDeletingFiles
Recursive
W/dalvikvm(26347): VFY: unable to resolve new-array 9713 ([Loth
er/writeily/ui/WrConfirmDialog$ConfirmDialogCallback;) in Lnet/
gsantner/opoc/ui/FilesystemViewerFragment;
D/dalvikvm(26347): VFY: replacing opcode 0x23 at 0x0068
I/dalvikvm(26347): Could not find method other.writeily.ui.WrRe
nameDialog.newInstance, referenced from method net.gsantner.opo
c.ui.FilesystemViewerFragment.onOptionsItemSelected
W/dalvikvm(26347): VFY: unable to resolve static method 65328:
Lother/writeily/ui/WrRenameDialog;.newInstance (Ljava/io/File;L
net/gsantner/opoc/util/Callback$a1;)Lother/writeily/ui/WrRename
Dialog;
D/dalvikvm(26347): VFY: replacing opcode 0x71 at 0x00d5
I/dalvikvm(26347): Failed resolving Lnet/gsantner/opoc/ui/Files
ystemViewerFragment$$ExternalSyntheticLambda8; interface 9375 '
Lother/writeily/ui/WrConfirmDialog$ConfirmDialogCallback;'
W/dalvikvm(26347): Link of class 'Lnet/gsantner/opoc/ui/Filesys
temViewerFragment$$ExternalSyntheticLambda8;' failed
E/dalvikvm(26347): Could not find class 'net.gsantner.opoc.ui.F
ilesystemViewerFragment$$ExternalSyntheticLambda8', referenced
from method net.gsantner.opoc.ui.FilesystemViewerFragment.onOpt
ionsItemSelected
W/dalvikvm(26347): VFY: unable to resolve new-instance 9176 (Ln
et/gsantner/opoc/ui/FilesystemViewerFragment$$ExternalSynthetic
Lambda8;) in Lnet/gsantner/opoc/ui/FilesystemViewerFragment;
D/dalvikvm(26347): VFY: replacing opcode 0x22 at 0x0194
I/dalvikvm(26347): Failed resolving Lnet/gsantner/opoc/ui/Files
ystemViewerFragment$$ExternalSyntheticLambda9; interface 9375 '
Lother/writeily/ui/WrConfirmDialog$ConfirmDialogCallback;'
W/dalvikvm(26347): Link of class 'Lnet/gsantner/opoc/ui/Filesys
temViewerFragment$$ExternalSyntheticLambda9;' failed
D/dalvikvm(26347): DexOpt: unable to opt direct call 0xfaac at
0x48 in Lnet/gsantner/opoc/ui/FilesystemViewerFragment;.importF
ile
I/dalvikvm(26347): Failed resolving Lnet/gsantner/opoc/ui/Files
ystemViewerFragment$$ExternalSyntheticLambda8; interface 9375 '
Lother/writeily/ui/WrConfirmDialog$ConfirmDialogCallback;'
W/dalvikvm(26347): Link of class 'Lnet/gsantner/opoc/ui/Filesys
temViewerFragment$$ExternalSyntheticLambda8;' failed
D/dalvikvm(26347): DexOpt: unable to opt direct call 0xfaaa at
0x196 in Lnet/gsantner/opoc/ui/FilesystemViewerFragment;.onOpti
onsItemSelected
I/dalvikvm(26347): Could not find method android.webkit.WebView
.enableSlowWholeDocumentDraw, referenced from method net.gsantn
er.markor.activity.DocumentEditFragment.onViewCreated
W/dalvikvm(26347): VFY: unable to resolve static method 5876: L
android/webkit/WebView;.enableSlowWholeDocumentDraw ()V
D/dalvikvm(26347): VFY: replacing opcode0x71 at 0x001d
I/dalvikvm(26347): Could not find method java.io.File.toPath, r
eferenced from method net.gsantner.markor.model.Document.lastMo
dified
W/dalvikvm(26347): VFY: unable to resolve virtual method 48856:
Ljava/io/File;.toPath ()Ljava/nio/file/Path;
D/dalvikvm(26347): VFY: replacing opcode 0x6e at 0x0008
I/dalvikvm(26347): Could not find method other.de.stanetz.jpenc
converter.JavaPasswordbasedCryption.getDecryptedText, reference
d from method net.gsantner.markor.model.Document.loadContent
W/dalvikvm(26347): VFY: unable to resolve static method 65317:
Lother/de/stanetz/jpencconverter/JavaPasswordbasedCryption;.get
DecryptedText ([B[C)Ljava/lang/String;
D/dalvikvm(26347): VFY: replacing opcode 0x71 at 0x0024
W/dalvikvm(26347): VFY: unable to resolve exception class 9368
(Lother/de/stanetz/jpencconverter/JavaPasswordbasedCryption$Enc
ryptionFailedException;)
W/dalvikvm(26347): VFY: unable to find exception handler at add
r 0x34
W/dalvikvm(26347): VFY:  rejected Lnet/gsantner/markor/model/Do
cument;.loadContent (Landroid/content/Context;)Ljava/lang/Strin
g;
W/dalvikvm(26347): VFY:  rejecting opcode 0x0d at 0x0034
W/dalvikvm(26347): VFY:  rejected Lnet/gsantner/markor/model/Do
cument;.loadContent (Landroid/content/Context;)Ljava/lang/Strin
g;
W/dalvikvm(26347): Verifier rejected class Lnet/gsantner/markor
/model/Document;
D/AndroidRuntime(26347): Shutting down VM
W/dalvikvm(26347): threadid=1: thread exiting with uncaught exc
eption (group=0xe5bedba8)
E/AndroidRuntime(26347): FATAL EXCEPTION: main
E/AndroidRuntime(26347): Process: net.gsantner.markor, PID: 263
47
E/AndroidRuntime(26347): java.lang.VerifyError: net/gsantner/ma
rkor/model/Document
E/AndroidRuntime(26347):        at net.gsantner.markor.activity
.DocumentEditFragment.newInstance(DocumentEditFragment.java:86)
E/AndroidRuntime(26347):        at net.gsantner.markor.activity
.MainActivity$SectionsPagerAdapter.getItem(MainActivity.java:47
4)
E/AndroidRuntime(26347):        at androidx.fragment.app.Fragme
ntPagerAdapter.instantiateItem(FragmentPagerAdapter.java:174)
E/AndroidRuntime(26347):        at net.gsantner.markor.activity
.MainActivity$SectionsPagerAdapter.instantiateItem(MainActivity
.java:453)
E/AndroidRuntime(26347):        at androidx.viewpager.widget.Vi
ewPager.addNewItem(ViewPager.java:1010)
E/AndroidRuntime(26347):        at androidx.viewpager.widget.Vi
ewPager.populate(ViewPager.java:1224)
E/AndroidRuntime(26347):        at androidx.viewpager.widget.Vi
ewPager.populate(ViewPager.java:1092)
E/AndroidRuntime(26347):        at androidx.viewpager.widget.Vi
ewPager.onMeasure(ViewPager.java:1622)
E/AndroidRuntime(26347):        at android.view.View.measure(Vi
ew.java:16521)
E/AndroidRuntime(26347):        at android.view.ViewGroup.measu
reChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime(26347):        at android.widget.FrameLayout.o
nMeasure(FrameLayout.java:310)
E/AndroidRuntime(26347):        at android.view.View.measure(Vi
ew.java:16521)
E/AndroidRuntime(26347):        at android.view.ViewGroup.measu
reChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime(26347):        at android.widget.FrameLayout.o
nMeasure(FrameLayout.java:310)
E/AndroidRuntime(26347):        at androidx.appcompat.widget.Co
ntentFrameLayout.onMeasure(ContentFrameLayout.java:145)
E/AndroidRuntime(26347):        at android.view.View.measure(Vi
ew.java:16521)
E/AndroidRuntime(26347):        at android.view.ViewGroup.measu
reChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime(26347):        at android.widget.FrameLayout.o
nMeasure(FrameLayout.java:310)
E/AndroidRuntime(26347):        at android.view.View.measure(Vi
ew.java:16521)
E/AndroidRuntime(26347):        at android.view.ViewGroup.measu
reChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime(26347):        at android.widget.FrameLayout.o
nMeasure(FrameLayout.java:310)
E/AndroidRuntime(26347):        at android.view.View.measure(Vi
ew.java:16521)
E/AndroidRuntime(26347):        at android.view.ViewGroup.measu
reChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime(26347):        at android.widget.FrameLayout.o
nMeasure(FrameLayout.java:310)
E/AndroidRuntime(26347):        at android.view.View.measure(Vi
ew.java:16521)
E/AndroidRuntime(26347):        at android.view.ViewGroup.measu
reChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime(26347):        at android.widget.FrameLayout.o
nMeasure(FrameLayout.java:310)
E/AndroidRuntime(26347):        at com.android.internal.policy.
impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
E/AndroidRuntime(26347):        at android.view.View.measure(Vi
ew.java:16521)
E/AndroidRuntime(26347):        at android.view.ViewRootImpl.pe
rformMeasure(ViewRootImpl.java:1912)
E/AndroidRuntime(26347):        at android.view.ViewRootImpl.me
asureHierarchy(ViewRootImpl.java:1109)
E/AndroidRuntime(26347):        at android.view.ViewRootImpl.pe
rformTraversals(ViewRootImpl.java:1291)
E/AndroidRuntime(26347):        at android.view.ViewRootImpl.do
Traversal(ViewRootImpl.java:996)
E/AndroidRuntime(26347):        at android.view.ViewRootImpl$Tr
aversalRunnable.run(ViewRootImpl.java:5600)
E/AndroidRuntime(26347):        at android.view.Choreographer$C
allbackRecord.run(Choreographer.java:761)
E/AndroidRuntime(26347):        at android.view.Choreographer.d
oCallbacks(Choreographer.java:574)
E/AndroidRuntime(26347):        at android.view.Choreographer.d
oFrame(Choreographer.java:544)
E/AndroidRuntime(26347):        at android.view.Choreographer$F
rameDisplayEventReceiver.run(Choreographer.java:747)
E/AndroidRuntime(26347):        at android.os.Handler.handleCal
lback(Handler.java:733)
E/AndroidRuntime(26347):        at android.os.Handler.dispatchM
essage(Handler.java:95)
E/AndroidRuntime(26347):        at android.os.Looper.loop(Loope
r.java:136)
E/AndroidRuntime(26347):        at android.app.ActivityThread.m
ain(ActivityThread.java:5001)
E/AndroidRuntime(26347):        at java.lang.reflect.Method.inv
okeNative(Native Method)
E/AndroidRuntime(26347):        at java.lang.reflect.Method.inv
oke(Method.java:515)
E/AndroidRuntime(26347):        at com.android.internal.os.Zygo
teInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
E/AndroidRuntime(26347):        at com.android.internal.os.Zygo
teInit.main(ZygoteInit.java:613)
E/AndroidRuntime(26347):        at dalvik.system.NativeStart.ma
in(Native Method)
D/dalvikvm(26347): GC_CONCURRENT freed 336K, 3% free 17644K/180
16K, paused 2ms+1ms, total 13ms
W/ActivityManager(25068):   Force finishing activity net.gsantn
er.markor/.activity.MainActivity
```
```

**Comment by gsantner** [comment]
Can you please select one of the green builds from here and download/install the attached android-apk? Does it crash there still?


<https://github.com/gsantner/markor/actions>

**Comment by ntninja** [comment]
CI #2048 / Commit 3f7427b, CI #2041 / Commit c121g51, and CI #2013 / Commit 56c6653 all crash with:

```
I/ActivityManager(26143): Start proc net.gsantner.markor_test for activity net.gsantner.markor_test/net.gsantner.markor.activity.MainActivity: pid=28402 uid=10059 gids={50059, 1028, 1015, 3003}
I/ActivityManager(26143): Killing 28355:com.android.packageinstaller/u0a16 (adj 9): remove task
D/ProcessState(28402): getContextObject - ALIEN_ID=[alien]
D/FakeHome(26329): onStop
D/alien_init(25965): Set process(pid = 28402) score_adj as [35]
D/ActivityManager(26143): handleAppDiedLocked app = ProcessRecord{e6efeb48 0:com.android.packageinstaller/u0a16}
D/ActivityManager(26143): getSurfaceToDestroyLocked, surfaceToDestroy = -1
D/ActivityManager(26143): handleAppDiedLocked app = ProcessRecord{e6efeb48 0:com.android.packageinstaller/u0a16}
D/ActivityManager(26143): getSurfaceToDestroyLocked, surfaceToDestroy = -1
D/AndroidRuntime(28402): Shutting down VM
W/dalvikvm(28402): threadid=1: thread exiting with uncaught exception (group=0xe5c4dba8)
E/AndroidRuntime(28402): FATAL EXCEPTION: main
E/AndroidRuntime(28402): Process: net.gsantner.markor_test, PID: 28402
E/AndroidRuntime(28402): java.lang.RuntimeException: Unable to get provider androidx.core.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/data/app/net.gsantner.markor_test-1.apk"],nativeLibraryDirectories=[/data/app-lib/net.gsantner.markor_test-1, /system/lib, /vendor/lib, /system_jolla/lib]]
E/AndroidRuntime(28402):        at android.app.ActivityThread.installProvider(ActivityThread.java:4777)
E/AndroidRuntime(28402):        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4369)
E/AndroidRuntime(28402):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4309)
E/AndroidRuntime(28402):        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime(28402):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime(28402):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(28402):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(28402):        at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(28402):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(28402):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(28402):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
E/AndroidRuntime(28402):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:613)
E/AndroidRuntime(28402):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(28402): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/data/app/net.gsantner.markor_test-1.apk"],nativeLibraryDirectories=[/data/app-lib/net.gsantner.markor_test-1, /system/lib, /vendor/lib, /system_jolla/lib]]
E/AndroidRuntime(28402):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(28402):        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime(28402):        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime(28402):        at android.app.ActivityThread.installProvider(ActivityThread.java:4762)
E/AndroidRuntime(28402):        ... 12 more
W/ActivityManager(26143):   Force finishing activity net.gsantner.markor_test/net.gsantner.markor.activity.MainActivity
```

**Comment by gsantner** [comment]
Ok, interesting 

> RuntimeException: Unable to get provider androidx.core.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" 

but then, also:

> on path: DexPathList[[zip file "/data/app/net.gsantner.markor_test-1.apk"],nativeLibraryDirectories=[/data/app-lib/net.gsantner.markor_test-1, /system/lib, /vendor/lib, /system_jolla/lib]]

it's a Jolla device (as you also posted in the description). thats a bit special compared to other android devices. will see if I can reproduce the error otherwise.

**Comment by gsantner** [comment]
Got a clue, please try <https://github.com/gsantner/markor/actions/runs/2908282324>

**Comment by ntninja** [comment]
The download would fail a few times this morning (truncated zip), but I tried it again now and it launches again. Guess it’s very very easy to forget enabling the compat library for the MultiDex workaround, when native Android support for MultiDex has been around for so long. :slightly_smiling_face: 

Thanks for resolving this so quickly! Markor is still so much better than anything natively available on SailfishOS, that being able to use it as an Android app is a blessing! :+1:

**Comment by gsantner** [comment]
So your jolla device had issues with downloading a zip file?^^
