### ISSUE TITLE
Null reference when resuming MainActivity

### ISSUE THREAD

**Issue by harshad1** [gsantner/markor#1858]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the bug still present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report - the change will be part of the next Markor update.

### Description

I get this when launching markor sometimes. I think it is because `_filesystemViewerAdapter` isn't being recreated correctly on restore or something.

It manifests as markor failing to launch, and the next tap starts it correctly, so this is not a critical bug imo. Just a little annoying.

```
FATAL EXCEPTION: main
Process: net.gsantner.markor, PID: 31747
java.lang.RuntimeException: Unable to resume activity {net.gsantner.markor/net.gsantner.markor.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void net.gsantner.opoc.frontend.filebrowser.GsFileBrowserListAdapter.setCurrentFolder(java.io.File, boolean)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4761)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4794)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void net.gsantner.opoc.frontend.filebrowser.GsFileBrowserListAdapter.setCurrentFolder(java.io.File, boolean)' on a null object reference
	at net.gsantner.markor.activity.MainActivity.onNewIntent(MainActivity.java:119)
	at android.app.Activity.performNewIntent(Activity.java:8067)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1429)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1442)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3836)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4744)
	... 13 more
```

### Steps to reproduce

1. Launch markor
2. Let markor sit in the background for a while
3. This happens sometimes when starting again

### Information

Android version: 12
Device: Pixel 3 xl
App Version: Latest master

### Source

git master branch

### Format / File type

Not specific

**Comment by gsantner** [comment]
Set/Restore/Cache last/current folder & title for toolbar is something that often makes issues yes

**Comment by gsantner** [comment]
Set/Restore/Cache last/current folder & title for toolbar is something that often makes issues yes. Got rework many times already^^.

Though have not got this one a single time

**Comment by harshad1** [comment]
I think it is because i use the widget as my primary entry point into markor

**Comment by gsantner** [comment]
Part of #1839 to my reading
