### ISSUE TITLE
Crash after adding three nested unordered Lists to markdown file

### ISSUE THREAD

**Issue by chromer030** [gsantner/markor#1897]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Notes after nested lists lead app to crash.
after creating more than three nested unordered lists (with 4 spaces)  , app crashes repeatedly after adding note to file , after removing nested ordering , no any crash any more.

example :

- this is a sample note
    - continue of note
    - another note
    - another one

### Steps to reproduce

1. Create a .md file
2. add  more than 3 nested unordered Lists
3. add new line and note.

### Information

Android version: 7.1.2 arm64
Device: Lenovo
App Version: 2.10.5

### Source

GitHub Releases

### Format / File type

Markdown

### Additional info / Log

```shell
adb logcat :


10-13 11:46:38.352 14981 15026 I [MALI][Gralloc]: [+]r_hnd(0x7f9da30ae0), client(92), share_fd(104)
10-13 11:46:38.509 14981 14981 D AndroidRuntime: Shutting down VM
10-13 11:46:38.513 14981 14981 E AndroidRuntime: FATAL EXCEPTION: main
10-13 11:46:38.513 14981 14981 E AndroidRuntime: Process: net.gsantner.markor, PID: 14981
10-13 11:46:38.513 14981 14981 E AndroidRuntime: java.lang.IndexOutOfBoundsException: 88, 1
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at android.text.PackedIntVector.getValue(Unknown Source)
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at android.text.DynamicLayout.getLineTop(Unknown Source)
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at android.text.Layout.getLineBaseline(Unknown Source)
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at net.gsantner.markor.frontend.textview.HighlightingEditor.updateHighlighting(HighlightingEditor.java:164)
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at net.gsantner.markor.frontend.textview.HighlightingEditor.lambda$setHighlighter$1(HighlightingEditor.java:192)
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at net.gsantner.markor.frontend.textview.HighlightingEditor.$r8$lambda$QJHrb_ReDeJHZdqOuDELYMI3vCs(HighlightingEditor.java)
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at net.gsantner.markor.frontend.textview.HighlightingEditor$$ExternalSyntheticLambda2.run(R8$$SyntheticClass)
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at android.os.Handler.handleCallback(Unknown Source)
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Unknown Source)
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at android.os.Looper.loop(Unknown Source)
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at android.app.ActivityThread.main(Unknown Source)
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(Unknown Source)
10-13 11:46:38.513 14981 14981 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(Unknown Source)
10-13 11:46:38.515   764  1565 W ActivityManager:   Force finishing activity net.gsantner.markor/.activity.DocumentActivity
10-13 11:46:38.519   764  1565 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:-1 com.android.server.am.AppErrors.crashApplicationInner:-1 com.android.server.am.AppErrors.crashApplication:-1 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:-1 com.android.server.am.ActivityManagerService.handleApplicationCrash:-1 
10-13 11:46:38.535   764   777 I memtrack_graphic: graphic_memtrack_get_memory match 4:      ion_mm_heap 14981    61440   3 ffffffc03d630400 ffffffc00815a540.
10-13 11:46:38.535   764   777 I memtrack_graphic:  : 14981 14981 61440 3 20480
10-13 11:46:38.535   764   777 I memtrack_graphic: graphic_memtrack_get_memory match 4:      ion_mm_heap 14981    61440   2 ffffffc05d2d8100 ffffffc00815a8c0.
10-13 11:46:38.535   764   777 I memtrack_graphic:  : 14981 14981 61440 2 51200
10-13 11:46:38.535   764   777 I memtrack_graphic: graphic_memtrack_get_memory match 4:      ion_mm_heap 14981  8355840   3 ffffffc067832f00 ffffffc0674a31c0.
10-13 11:46:38.535   764   777 I memtrack_graphic:  : 14981 14981 8355840 3 2836480
10-13 11:46:38.535   764   777 I memtrack_graphic: graphic_memtrack_get_memory match 4:      ion_mm_heap 14981  8355840   2 ffffffc062065300 ffffffc0674a3380.
10-13 11:46:38.535   764   777 I memtrack_graphic:  : 14981 14981 8355840 2 7014400
10-13 11:46:38.535   764   777 I memtrack_graphic: graphic_memtrack_get_memory match 4:      ion_mm_heap 14981  8355840   2 ffffffc03abc5500 ffffffc07262ee00.
10-13 11:46:38.535   764   777 I memtrack_graphic:  : 14981 14981 8355840 2 11192320
10-13 11:46:38.553 14981 14992 I art     : Background sticky concurrent mark sweep GC freed 7704(919KB) AllocSpace objects, 0(0B) LOS objects, 19% free, 3MB/4MB, paused 15.693ms total 51.180ms
10-13 11:46:38.578  1466  1477 I PerfService: PerfServiceNative_getPackName
10-13 11:46:38.593   764 13424 I OpenGLRenderer: Initialized EGL, version 1.4
10-13 11:46:38.593   764 13424 D OpenGLRenderer: Swap behavior 1
10-13 11:46:38.580 13424 13424 I RenderThread: type=1400 audit(0.0:378): avc: denied { ioctl } for path="/dev/mali0" dev="tmpfs" ino=1065 ioctlcmd=8218 scontext=u:r:system_server:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
10-13 11:46:38.604   301   737 I [MALI][Gralloc]: [+]hnd(0x7f78815e60), client(18), share_fd(63), hnd->flags:4
10-13 11:46:38.608   301   737 I [MALI][Gralloc]: [+]hnd(0x7f78816220), client(18), share_fd(67), hnd->flags:4
10-13 11:46:38.580 13424 13424 I RenderThread: type=1400 audit(0.0:379): avc: denied { read write } for path="/dev/mali0" dev="tmpfs" ino=1065 scontext=u:r:system_server:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
10-13 11:46:38.610   301   737 I [MALI][Gralloc]: [+]hnd(0x7f788167c0), client(18), share_fd(91), hnd->flags:4
10-13 11:46:38.613   764 13424 D mali_winsys: new_window_surface returns 0x3000
10-13 11:46:38.618   301  1883 I [MALI][Gralloc]: [-]hnd(0x7f788167c0), client(18), share_fd(91)
10-13 11:46:38.622   301  1883 I [MALI][Gralloc]: [+]hnd(0x7f788167c0), client(18), share_fd(110), hnd->flags:4
10-13 11:46:38.624   764 13424 E linker  : readlink("/proc/self/fd/232") failed: Permission denied [fd=232]
10-13 11:46:38.624   764 13424 E linker  : warning: unable to get realpath for the library "/system/lib64/hw/gralloc.mt6752.so". Will use given path.
10-13 11:46:38.624   764 13424 I [MALI][Gralloc]: [+]r_hnd(0x7f7366b6e0), client(148), share_fd(230)
10-13 11:46:38.633   301  1883 I [MALI][Gralloc]: [-]hnd(0x7f78816220), client(18), share_fd(67)
10-13 11:46:38.636   301  1883 I [MALI][Gralloc]: [+]hnd(0x7f78816220), client(18), share_fd(66), hnd->flags:4
10-13 11:46:38.638   764 13424 E linker  : readlink("/proc/self/fd/235") failed: Permission denied [fd=235]
10-13 11:46:38.638   764 13424 E linker  : warning: unable to get realpath for the library "/system/lib64/hw/gralloc.mt6752.so". Will use given path.
10-13 11:46:38.638   764 13424 I [MALI][Gralloc]: [+]r_hnd(0x7f7cb412c0), client(148), share_fd(233)
10-13 11:46:38.644   301  1883 I [MALI][Gralloc]: [-]hnd(0x7f78815e60), client(18), share_fd(63)
10-13 11:46:38.647   301  1883 I [MALI][Gralloc]: [+]hnd(0x7f78815e60), client(18), share_fd(63), hnd->flags:4
10-13 11:46:38.649   764 13424 E linker  : readlink("/proc/self/fd/237") failed: Permission denied [fd=237]
10-13 11:46:38.649   764 13424 E linker  : warning: unable to get realpath for the library "/system/lib64/hw/gralloc.mt6752.so". Will use given path.
10-13 11:46:38.650   764 13424 I [MALI][Gralloc]: [+]r_hnd(0x7f7cb41cc0), client(148), share_fd(235)
10-13 11:46:38.653   764  1565 W ActivityManager:   Force finishing activity net.gsantner.markor/.activity.DocumentActivity
10-13 11:46:38.660   764 13424 E linker  : readlink("/proc/self/fd/228") failed: Permission denied [fd=228]
10-13 11:46:38.660   764 13424 E linker  : warning: unable to get realpath for the library "/system/lib64/hw/gralloc.mt6752.so". Will use given path.
10-13 11:46:38.661   764 13424 I [MALI][Gralloc]: [-]r_hnd(0x7f7cb41cc0), client(148), share_fd(235)
10-13 11:46:38.662   764 13424 E linker  : readlink("/proc/self/fd/227") failed: Permission denied [fd=227]
10-13 11:46:38.662   764 13424 E linker  : warning: unable to get realpath for the library "/system/lib64/hw/gralloc.mt6752.so". Will use given path.
10-13 11:46:38.662   764 13424 I [MALI][Gralloc]: [-]r_hnd(0x7f7cb412c0), client(148), share_fd(233)
10-13 11:46:38.663   764 13424 E linker  : readlink("/proc/self/fd/227") failed: Permission denied [fd=227]
10-13 11:46:38.663   764 13424 E linker  : warning: unable to get realpath for the library "/system/lib64/hw/gralloc.mt6752.so". Will use given path.
10-13 11:46:38.664   764 13424 I [MALI][Gralloc]: [-]r_hnd(0x7f7366b6e0), client(148), share_fd(230)
10-13 11:46:38.664   301   737 I [MALI][Gralloc]: [-]hnd(0x7f78815e60), client(18), share_fd(63)
10-13 11:46:38.665   301   737 I [MALI][Gralloc]: [-]hnd(0x7f788167c0), client(18), share_fd(110)
10-13 11:46:38.665   764  1565 W ActivityManager:   Force finishing activity net.gsantner.markor/.activity.MainActivity
10-13 11:46:38.688   764  1565 E ActivityManager: Found activity ActivityRecord{f49746d u0 net.gsantner.markor/.activity.MainActivity t18 f} in proc activity list using null instead of expected ProcessRecord{4597c58 14981:net.gsantner.markor/u0a196}
10-13 11:46:38.695   764  1565 I ActivityManager: Killing 14981:net.gsantner.markor/u0a196 (adj 199): crash
10-13 11:46:38.695   764  1565 D ActivityManager: cleanUpApplicationRecord -- 14981
10-13 11:46:38.697   764   779 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
10-13 11:46:38.698   764   779 W ViewRootImpl[markor]: Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=454.5541, y[0]=805.18054, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=622476, downTime=622466, deviceId=7, source=0x1002 }
10-13 11:46:38.698   764   779 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
10-13 11:46:38.700   764   785 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
10-13 11:46:38.702   301   301 I [MALI][Gralloc]: [-]hnd(0x7f78c43cc0), client(18), share_fd(26)
10-13 11:46:38.703   301   301 I [MALI][Gralloc]: [-]hnd(0x7f78c43d60), client(18), share_fd(32)
10-13 11:46:38.703   301   301 I [MALI][Gralloc]: [-]hnd(0x7f78c43c20), client(18), share_fd(38)
10-13 11:46:38.703   301   301 I [MALI][Gralloc]: [-]hnd(0x7f788164a0), client(18), share_fd(35)
10-13 11:46:38.704   301   301 I [MALI][Gralloc]: [-]hnd(0x7f78816220), client(18), share_fd(66)
10-13 11:46:38.706   301   301 I [MALI][Gralloc]: [-]hnd(0x7f78816180), client(18), share_fd(55)
10-13 11:46:38.706   301   301 I [MALI][Gralloc]: [-]hnd(0x7f78c43ea0), client(18), share_fd(29)
10-13 11:46:38.708  1610  1610 D Launcher.Utilities: onLauncherStart: 0
```
```

**Comment by harshad1** [comment]
I can't reproduce it. I can't even think of what might cause it.

Could you try this with (a) Dynamic highlighting turned off (Settings / General) and (b) All highlighting turned off (In the file options menu)?

**Comment by chromer030** [comment]
No more crash in 2.10.6 , i close the issue for now as it's hard to reproduce , if i found more clues on how this bug happens i will reopen it , btw thank you devs for this great app.
