### ISSUE TITLE
I built the app in android studio and it always crash on start.  

### ISSUE THREAD

**Issue by ELY3M** [gsantner/markor#1964]
I think I am missing something?       

* App version: Latest commit from this repo - I did git clone from this repo and built it in Android Studio
* Android version/rom: Android 13 
* Device: Samsung S21+  

## Explain the Problem
the app always crash on start.           

## Steps to Reproduce
I built the app in Android Studio.    
Tap on app and it will just crash.  

I may be missing something??????       

## Log
2023-01-29 11:08:11.024 AndroidRuntime          pid-4266                             E  FATAL EXCEPTION: main
                                                                                        Process: net.gsantner.markor, PID: 4266
                                                                                        java.lang.NullPointerException: Attempt to read from field 'androidx.fragment.app.FragmentManager androidx.fragment.app.Fragment.mFragmentManager' on a null object reference in method 'void androidx.fragment.app.FragmentManager.putFragment(android.os.Bundle, java.lang.String, androidx.fragment.app.Fragment)'
                                                                                        	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:936)
                                                                                        	at net.gsantner.markor.activity.MainActivity.onSaveInstanceState(MainActivity.java:121)
                                                                                        	at android.app.Activity.performSaveInstanceState(Activity.java:2265)
                                                                                        	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1563)
                                                                                        	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:6487)
                                                                                        	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5862)
                                                                                        	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5796)
                                                                                        	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5893)
                                                                                        	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
                                                                                        	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                        	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                                                                                        	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                        	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
                                                                                        	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                        	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                        	at android.os.Looper.loop(Looper.java:313)
                                                                                        	at android.app.ActivityThread.main(ActivityThread.java:8741)
                                                                                        	at java.lang.reflect.Method.invoke(Native Method)
                                                                                        	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
2023-01-29 11:08:11.351 WindowManager           pid-989                              E  win=Window{bdd21ad u0 net.gsantner.markor/net.gsantner.markor.activity.IntroActivity EXITING} destroySurfaces: appStopped=false cleanupOnResume=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.ActivityRecord.destroySurfaces:6428 com.android.server.wm.ActivityRecord.destroySurfaces:6409 com.android.server.wm.WindowState.onExitAnimationDone:5915 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda11.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.ActivityRecord.onAnimationFinished:8436 com.android.server.wm.ActivityRecord.postApplyAnimation:6142 
2023-01-29 11:08:11.351 WindowManager           pid-989                              E  win=Window{bb244d6 u0 Splash Screen net.gsantner.markor EXITING} destroySurfaces: appStopped=false cleanupOnResume=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=8 caller=com.android.server.wm.WindowState.onExitAnimationDone:5917 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda11.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.ActivityRecord.onAnimationFinished:8436 com.android.server.wm.ActivityRecord.postApplyAnimation:6142 com.android.server.wm.ActivityRecord.commitVisibility:6114 com.android.server.wm.ActivityRecord.commitVisibility:6118

**Comment by gsantner** [comment]
No, might be just that you discovered a  bug. Might also be already being fixed by a open merge request.

**Comment by ELY3M** [comment]
I decided to update android studio and it asked me to upgrade the project.  so I go ahead with upgrade. 
it look like upgrading fixed the issue.
