### ISSUE TITLE
Add fileformat CSV to view/export as a html table

### ISSUE THREAD

**Issue by k3b** [gsantner/markor#1980]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

[CSV Files](https://en.wikipedia.org/wiki/Comma-separated_values) are plain-text files that are used to import and export tabular data from other apps. Many spreadsheet applications like MS-Excel or Libre-Office-Calc can read and write csv.

It would be great if Markor can preview/export csv files as html-tables.

---

Implementation details:

on android csv files can use these mimeTypes

* `text/csv` see https://www.rfc-editor.org/rfc/rfc7111
* `text/comma-separated-values` non standard but used by android filemanager

----

There is a java lib that can read and write csv at https://opencsv.sourceforge.net/ (License Apache 2)
Gradle dependency `implementation 'com.opencsv:opencsv:5.7.1'`

I have successfully used the lib in https://github.com/SecUSo/privacy-friendly-finance-manager/pull/52

### Information

Android version: 10
Device: lg
App Version: (F-Droid) 2.10.7

### Source

F-Droid

### Format / File type

Something else (-> Additional info)

### Additional info / Log

```shell
[CSV File](https://en.wikipedia.org/wiki/Comma-separated_values) 

mimeTypes

* `text/csv` see https://www.rfc-editor.org/rfc/rfc7111
* `text/comma-separated-values` non standard but used by android filemanager
```

**Comment by k3b** [comment]
Related : https://github.com/gsantner/markor/discussions/1667

**Comment by gsantner** [comment]
You can open csv with Markor generally as it is currently.

So what this is about is to add a own view-mode/text-converter implementation specific to CSV.

**Comment by k3b** [comment]
@gsantner i just downloaded the sources from https://github.com/gsantner/markor/ master compiled and run the unmodified sources 

> gradle clean
> gradle InstallFlavorDefaultDebug

on my android-10 app immediatly crashes  (the app cannot be started) with this logcat

<pre>
2023-02-17 18:28:27.455  6895-6895  AndroidRuntime          net.gsantner.markor                  E  FATAL EXCEPTION: main
	Process: net.gsantner.markor, PID: 6895
	java.lang.NullPointerException: Attempt to read from field 'androidx.fragment.app.FragmentManager androidx.fragment.app.Fragment.mFragmentManager' on a null object reference
		at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:936)
		at net.gsantner.markor.activity.MainActivity.onSaveInstanceState(MainActivity.java:119)
		at android.app.Activity.performSaveInstanceState(Activity.java:2049)
		at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1486)
		at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5454)
		at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4746)
		at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4710)
		at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4785)
		at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
		at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
		at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
		at android.os.Handler.dispatchMessage(Handler.java:107)
		at android.os.Looper.loop(Looper.java:214)
		at android.app.ActivityThread.main(ActivityThread.java:7615)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
<pre>

is the current "master" content runnable or is there something if have to think about ?

----

if i compile and run from android studio the app also crashes
the app with title "Marder" immediatly

2023-02-17 18:34:12.987  7316-7316  AndroidRuntime          net.gsantner.markor_test             E  FATAL EXCEPTION: main
	Process: net.gsantner.markor_test, PID: 7316
	java.lang.NullPointerException: Attempt to read from field 'androidx.fragment.app.FragmentManager androidx.fragment.app.Fragment.mFragmentManager' on a null object reference
		at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:936)
		at net.gsantner.markor.activity.MainActivity.onSaveInstanceState(MainActivity.java:119)
		at android.app.Activity.performSaveInstanceState(Activity.java:2049)
		at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1486)
		at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5454)
		at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4746)
		at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4710)
		at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4785)
		at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
		at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
		at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
		at android.os.Handler.dispatchMessage(Handler.java:107)
		at android.os.Looper.loop(Looper.java:214)
		at android.app.ActivityThread.main(ActivityThread.java:7615)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2023-02-17 18:34:13.031  7316-7316  Process                 net.gsantner.markor_test             I  Sending signal. PID: 7316 SIG: 9

**Comment by k3b** [comment]
From my point of view: Implementation completed. Waiting for merge.

Follow up ticket https://github.com/gsantner/markor/issues/1987 for CsvSyntaxHighlighter
