### ISSUE TITLE
Error: Could not open file

### ISSUE THREAD

**Issue by Mo-1996** [gsantner/markor#2301]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

I inserted a list symbol in the file, but after viewing it, it appears as an empty file when saved
[untitled.webm](https://github.com/gsantner/markor/assets/46777154/37e8aa44-39d2-48ae-ac62-f9d7fdba7e5f)

### Steps to reproduce

1.  Open an MD file and insert the Unordered list
2. click view mode and back
3. Display "Error: Could not open file"
4. Click on the file, there is nothing

### Information

Android version: 8.1
Device: Nexus 5X
App Version: v2.12.0(149)

### Source

GitHub Releases

### Format / File type

Markdown

### Additional info / Log

```shell
W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.f(PG:314)
        at org.chromium.android_webview.AwContents.a(PG:288)
        at org.chromium.android_webview.AwContents.q(PG:544)
        at agE.loadingStateChanged(PG:159)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by gsantner** [comment]
Seems like your operating system ships a non-working WebView.

**Comment by gsantner** [comment]
Seems like your operating system ships a non-working WebView.

By the way, Android 8.1 is stoneage old and insecure. You have the luck that your device is capable of running the most recent Android version too <https://xdaforums.com/f/nexus-5x-original-android-development.4742/>

**Comment by gsantner** [comment]
> Click on the file, there is nothing

That is actually due Markor doesn't automatically save what looks to be a faulty text, so less then 3 characters. You can press the save button manually however to save it like that explicitly.
