### ISSUE TITLE
App crashes on clicking the "recently viewed documents" option

### ISSUE THREAD

**Issue by neupanedipen** [gsantner/markor#271]
#### Expected behavior<br>
The app must be stable on clicking the &quot;recently viewed documents&quot; options even when there are no any documents viewed.<br>
#### Actual behavior<br>
But the app crashes when I click on the &quot;recently viewed documents&quot; icon from the top bar when I have no documents viewed.<br>
#### How to reproduce<br>
1. Install the app and launch it. <br>
2. Click on history icon from the rop right corner of the app.<br>
(Make sure you have no any documents created or viewed before clicking this option)<br>![](https://s19.postimg.cc/4b3c2sts3/20180601_011610.png)
The app crashes.<br>
* App Version: 0.3.9<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/fBPOFrL6ClI
##### logcat
``` 
FATAL EXCEPTION: main
Process: net.gsantner.markor, PID: 20018
java.lang.IndexOutOfBoundsException: setSpan (-1 ... 0) starts before 0
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1023)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:594)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:590)
	at net.gsantner.markor.ui.SearchOrCustomTextDialogCreator.showRecentDocumentsDialog(SearchOrCustomTextDialogCreator.java:59)
	at net.gsantner.markor.activity.MainActivity.onOptionsItemSelected(MainActivity.java:165)
	at android.app.Activity.onMenuItemSelected(Activity.java:2708)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:407)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
	at android.view.View.performClick(View.java:4633)
	at android.view.View$PerformClick.run(View.java:19280)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5598)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by gsantner** [comment]
Happens when you never have opened anything at all. one line fixed.
