### ISSUE TITLE
Markor can not write or change the file to a SD memory card

### ISSUE THREAD

**Issue by Geeorg** [gsantner/markor#290]
#### General information

* **App version:** Markor 0.3.10 (24)
* **System:** Android 6.0.1 and 7.0

#### Description

Markor can not write or change the file to a SD memory card `/storage/xxxx-xxx/_test.md`.
Changing the file to internal memory `/storage/emulated/0/_test.md` is normal.
For me this is a big problem.

#### Log

<details>
  <summary>adb logcat | findstr net.gsantner.markor</summary>

```
07-01 11:46:54.704  2767  4054 D ActivityManager: removeProcessNameLocked mProcessNames.remove pid=510 ,hash=53645499 ,name=net.gsantner.markor
07-01 11:46:54.704  2767  4054 I ActivityManager: Killing 510:net.gsantner.markor/u0a110 (adj 15): permissions revoked
07-01 11:46:54.714  2767  4054 D PackageManager: Revoked a runtime permission: android.permission.READ_EXTERNAL_STORAGE (package: net.gsantner.markor, callingUid: 10008, callingPid: 1401)
07-01 11:46:54.749  2767  4314 D PackageManager: Revoked a runtime permission: android.permission.WRITE_EXTERNAL_STORAGE (package: net.gsantner.markor, callingUid: 10008, callingPid: 1401)
07-01 11:46:56.534  2767  4013 D MountService: onExternalStoragePolicyChanged : uid=10110, packageName=net.gsantner.markor
07-01 11:46:56.539  2767  4013 D MountService: getExternalStorageMountMode : final mountMode=2, uid : 10110, packageName : net.gsantner.markor
07-01 11:46:56.589  2767  4314 D MountService: onExternalStoragePolicyChanged : uid=10110, packageName=net.gsantner.markor
07-01 11:46:56.589  2767  4314 D MountService: getExternalStorageMountMode : final mountMode=3, uid : 10110, packageName : net.gsantner.markor
07-01 11:47:21.224 19544 19544 I Timeline: Timeline: Activity_launch_request id:net.gsantner.markor time:54667552
07-01 11:47:21.239  2767  3224 D GameManagerService: identifyGamePackage. net.gsantner.markor
07-01 11:47:21.239  2767  3224 D MultiWindowPolicy: Gamemode - return -1,  when calling  identifyForegroundApp(net.gsantner.markor)
07-01 11:47:21.244  2767  3224 V WindowManager: addAppToken: AppWindowToken{ee7680f token=Token{f20796e ActivityRecord{83d88e9 u0 net.gsantner.markor/.activity.DocumentActivity t925}}} to stack=1 task=925 at 0
07-01 11:47:21.314  2767  4314 D MountService: getExternalStorageMountMode : final mountMode=3, uid : 10110, packageName : net.gsantner.markor
07-01 11:47:21.354  2767  4314 I ActivityManager: Start proc 2260:net.gsantner.markor/u0a110 for activity net.gsantner.markor/.activity.DocumentActivity
07-01 11:47:21.379  2767  3002 V WindowStateAnimator: Finishing drawing window Window{28a4a07 u0 d0 p2767 Starting net.gsantner.markor}: mDrawState=DRAW_PENDING
07-01 11:47:21.379  2260  2260 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=net.gsantner.markor
07-01 11:47:21.449  2767  2782 D ActivityManager:  Launching net.gsantner.markor, updated priority
07-01 11:47:21.459  2767  2767 D GameManagerService: NotifyRunnable. pkg: net.gsantner.markor, type: 4, isMinimized: false, isTunableApp: false
07-01 11:47:21.479  2767  2908 D StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{28a4a07 u0 d0 p2767 Starting net.gsantner.markor}
07-01 11:47:21.499  2260  2260 W System  : ClassLoader referenced unknown path: /data/app/net.gsantner.markor-2/lib/arm
07-01 11:47:22.224  2260  2328 D libGLESv1: STS_GLApi : DTS is not allowed for Package : net.gsantner.markor
07-01 11:47:22.289  2260  2299 D libGLESv2: STS_GLApi : DTS is not allowed for Package : net.gsantner.markor
07-01 11:47:22.354  2767  4002 V WindowStateAnimator: Finishing drawing window Window{83f232 u0 d0 p2260 net.gsantner.markor/net.gsantner.markor.activity.DocumentActivity}: mDrawState=DRAW_PENDING
07-01 11:47:22.364  2767  3002 I ActivityManager: Displayed net.gsantner.markor/.activity.DocumentActivity: +1s52ms
07-01 11:47:22.364  2767  3002 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{83d88e9 u0 net.gsantner.markor/.activity.DocumentActivity t925} time:54668693
07-01 11:47:22.424  2767  2780 V WindowStateAnimator: Finishing drawing window Window{83f232 u0 d0 p2260 net.gsantner.markor/net.gsantner.markor.activity.DocumentActivity}: mDrawState=HAS_DRAWN
07-01 11:47:22.454  2260  2344 W cr_CrashFileManager: /data/user/0/net.gsantner.markor/cache/WebView/Crash Reports does not exist or is not a directory
07-01 11:47:24.949  5276  5276 I LatinIme: onActivate() : EditorInfo = Package = net.gsantner.markor : Type = Text : Learning = Enable : Suggestion = Show : AutoCorrection = Enable : Microphone = Show : Incognito = Disable
07-01 11:47:26.479  2767  5721 D GameManagerService: identifyGamePackage. net.gsantner.markor
07-01 11:47:26.484  2767  5721 D GameManagerService: identifyGamePackage. net.gsantner.markor
07-01 11:47:28.454  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:47:28.454  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:47:28.454  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentActivity.saveDocument(DocumentActivity.java:388)
07-01 11:47:28.454  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentActivity.onOptionsItemSelected(DocumentActivity.java:176)
07-01 11:47:28.934  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:47:28.934  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:47:28.934  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentActivity.saveDocument(DocumentActivity.java:388)
07-01 11:47:28.934  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentActivity.onOptionsItemSelected(DocumentActivity.java:176)
07-01 11:47:29.309  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:47:29.309  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:47:29.309  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentActivity.saveDocument(DocumentActivity.java:388)
07-01 11:47:29.309  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentActivity.onOptionsItemSelected(DocumentActivity.java:176)
07-01 11:47:29.494  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:47:29.494  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:47:29.494  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentActivity.saveDocument(DocumentActivity.java:388)
07-01 11:47:29.494  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentActivity.onOptionsItemSelected(DocumentActivity.java:176)
07-01 11:47:29.734  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:47:29.734  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:47:29.734  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentActivity.saveDocument(DocumentActivity.java:388)
07-01 11:47:29.734  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentActivity.onOptionsItemSelected(DocumentActivity.java:176)
07-01 11:47:29.969  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:47:29.969  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:47:29.969  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentActivity.saveDocument(DocumentActivity.java:388)
07-01 11:47:29.969  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentActivity.onOptionsItemSelected(DocumentActivity.java:176)
07-01 11:47:31.489  2767  5721 D GameManagerService: identifyGamePackage. net.gsantner.markor
07-01 11:47:31.499  2767  5721 D GameManagerService: identifyGamePackage. net.gsantner.markor
07-01 11:47:32.664  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:47:32.664  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:47:32.664  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.onOptionsItemSelected(DocumentEditFragment.java:181)
07-01 11:47:33.259  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:47:33.259  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:47:33.259  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.onOptionsItemSelected(DocumentEditFragment.java:181)
07-01 11:47:33.494  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:47:33.494  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:47:33.494  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.onOptionsItemSelected(DocumentEditFragment.java:181)
07-01 11:47:33.704  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:47:33.704  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:47:33.704  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.onOptionsItemSelected(DocumentEditFragment.java:181)
07-01 11:47:33.904  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:47:33.904  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:47:33.904  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.onOptionsItemSelected(DocumentEditFragment.java:181)
07-01 11:48:25.589  2767  2902 E ActivityManager:   4.1% 2260/net.gsantner.markor: 2.8% user + 1.3% kernel / faults: 175 minor
07-01 11:49:35.524  2767  2902 E ActivityManager:   4% 2260/net.gsantner.markor: 2.3% user + 1.6% kernel / faults: 1355 minor
07-01 11:50:52.929  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:50:52.929  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:50:52.929  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.onOptionsItemSelected(DocumentEditFragment.java:181)
07-01 11:50:53.824  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:50:53.824  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:50:53.824  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.onOptionsItemSelected(DocumentEditFragment.java:181)
07-01 11:50:54.409  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:50:54.409  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:50:54.409  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.onOptionsItemSelected(DocumentEditFragment.java:181)
07-01 11:53:11.909  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:53:11.909  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:53:11.909  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.onPause(DocumentEditFragment.java:302)
07-01 11:53:11.964  2260  2260 W System.err:    at net.gsantner.markor.util.DocumentIO.saveDocument(DocumentIO.java:143)
07-01 11:53:11.964  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.saveDocument(DocumentEditFragment.java:277)
07-01 11:53:11.964  2260  2260 W System.err:    at net.gsantner.markor.activity.DocumentEditFragment.onSaveInstanceState(DocumentEditFragment.java:285)
07-01 11:53:11.969  5276  5276 I LatinIme: onActivate() : EditorInfo = Package = net.gsantner.markor : Type = Text : Learning = Enable : Suggestion = Show : AutoCorrection = Enable : Microphone = Show : Incognito = Disable
07-01 11:53:12.324  2767  3995 V WindowStateAnimator: Finishing drawing window Window{69aeade u0 d0 p2260 net.gsantner.markor/net.gsantner.markor.activity.DocumentActivity}: mDrawState=DRAW_PENDING
07-01 11:53:12.329  2767  3002 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{83d88e9 u0 net.gsantner.markor/.activity.DocumentActivity t925} time:55018657
07-01 11:53:12.349  2767  4048 V WindowStateAnimator: Finishing drawing window Window{69aeade u0 d0 p2260 net.gsantner.markor/net.gsantner.markor.activity.DocumentActivity}: mDrawState=HAS_DRAWN
07-01 11:53:18.769  2767  4054 V WindowStateAnimator: Finishing drawing window Window{33c8745 u0 d0 p2260 net.gsantner.markor/net.gsantner.markor.activity.DocumentActivity}: mDrawState=DRAW_PENDING
07-01 11:53:18.774  2767  3002 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{83d88e9 u0 net.gsantner.markor/.activity.DocumentActivity t925} time:55025100
07-01 11:53:18.779  2767  3002 I WindowManager: Screen frozen for +423ms due to Window{33c8745 u0 d0 p2260 net.gsantner.markor/net.gsantner.markor.activity.DocumentActivity}
07-01 11:53:18.804  2767  4314 V WindowStateAnimator: Finishing drawing window Window{33c8745 u0 d0 p2260 net.gsantner.markor/net.gsantner.markor.activity.DocumentActivity}: mDrawState=HAS_DRAWN
07-01 11:53:20.934  2767  5721 D SurveyLogging: app_id = com.android.server.ssrm, feature = CHAR, extra = {"SIOP":"0", "PST_TMP":"355", "BAT_TMP":"357", "CHG_TMP":"0", "PA_TMP":"0", "BAT_LV":"70", "BAT_CUR":"-796", "RSSI":"-103", "RAD_DAT":"0", "WIFI_DAT":"946659", "BRI":"227", "CHR_TYPE":"2", "KNOX":"false", "SCRN":"true", "RAD":"2", "CALL":"false", "CF":"-1", "GF":"-1", "CG":"100", "TOP_PROC":"com.google.android.gms", "TOP_USE":"23", "FOR_PKG":"net.gsantner.markor"}
07-01 11:53:21.794  2260  2260 V ActivityThread: updateVisibility : ActivityRecord{5efd1ff token=android.os.BinderProxy@4f7e6ab {net.gsantner.markor/net.gsantner.markor.activity.DocumentActivity}} show : true
07-01 11:53:26.099  2767  2908 D StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{33c8745 u0 d0 p2260 net.gsantner.markor/net.gsantner.markor.activity.DocumentActivity}
07-01 11:53:26.159  2767  4002 D ActivityManager:  Launching net.gsantner.markor, updated priority
07-01 11:53:26.169  2767  2767 D GameManagerService: NotifyRunnable. pkg: net.gsantner.markor, type: 4, isMinimized: false, isTunableApp: false
07-01 11:53:26.379  2767  5721 D GameManagerService: identifyGamePackage. net.gsantner.markor
07-01 11:53:26.379  2767  5721 D GameManagerService: identifyGamePackage. net.gsantner.markor
07-01 11:53:26.384  2767  5721 D GameManagerService: identifyGamePackage. net.gsantner.markor
```

</details>

**Comment by MrErr** [comment]
I have this same problem too. Have you found any workarounds?

**Comment by thousandsofthem** [comment]
Same problem

**Comment by FBachofner** [comment]
I have had the same problem ever since first trying Markor.   This is on Android 7.1.1 and Markor Has been given the "storage" permission in app settings.

Like the original poster,  I am on Markor 0.3.10

**Comment by gsantner** [comment]
Heres a small writeup on that: There is NOTHING markor or any other non-root app can do about that. Android is designed that way that apps cannot write just everywhere they want, and so Markor. I call that stupid for userdata like sdcard but that was not my decision. Even more there are about 5 different ways to write files across all yet available Android versions, and even that is not standardized access as device vendors in the end control paths and mounts (like external storage).

**What I have developed now**

* Editor
  * Show prominent warning ahead if not writeable
* fileselectiondialog (import, select root, quicknote, todo etc)
  * mark things red that cannot be written to
  * supply all writeable folders of available storages at storage selection folder (just press `..` go up multiple times)
  * These new writeable sdcard folder-shortcuts lead to one folder that will be writeable on all devices. This is `/storage/SDCARDNAME/Android/data/net.gsantner.markor/files/` (of course you have to insert a real sdcard and it must be mounted etc)
  * These shortcurts are noticeable by the ending `(app folder)` at the end

**What you should do**
* now: Lookup the said path if you want to use sdcard and select that manually as root/special-file
* when update is out: Same but just go up till you reach `storage`s, there will be all shortcuts to all useable paths (written in black)

About the real problem, that sdcard is not writeable, I cannot do anything about, don't blame me or Markor. There are enough discussion and and rant threads about that. I will not respond to future comments about `I cannot write to sd` or `have same problem with sd` here. Again, I and no other app dev else can fix it.

**All I can say now is - wait for it. Update is scheduled, it will be 1.0.0**


<table><tr><td><img src="https://user-images.githubusercontent.com/6735650/43995963-7ad186fa-9db9-11e8-93c3-67ee73fd2bd6.png"></td><td><img src="https://user-images.githubusercontent.com/6735650/43995960-5d683924-9db9-11e8-9909-ec13329f39b8.png"></td></tr>

**Comment by thousandsofthem** [comment]
Re: warning - current version do not show anything, it looks like it saved correctly.

Re: "NOTHING markor or any other non-root app can do about" - other apps, like QuickEdit editor fixed it somehow, in exactly the same situation. Unfortunately don't know the solution

**Comment by gsantner** [comment]
> Re: warning - current version do not show anything, it looks like it saved correctly.

You didnt read text. Wait for update.

> Re: "NOTHING markor or any other non-root app can do about" - other apps, like QuickEdit editor fixed it somehow, in exactly the same situation. Unfortunately don't know the solution

You can use root permission to edit them (to dangerous!) or maybe some dirty hacks or hidden APIs to get access. I don't want to do that, none of them.

**Comment by gsantner** [comment]
My phone is anyway damaged, need a new one. Probably will go for XZ2 Compact (<https://www.sonymobile.com/at/products/phones/xperia-xz2-compact/>), which has SD slot. Maybe I will have some findings there.
