### ISSUE TITLE
Cannot add new Jekyll Post

### ISSUE THREAD

**Issue by davidoe** [gsantner/markor#455]
#### General information

* **App version:** 1.5.0 F-Droid
* **System:** Android 6.0.1, Samsung S5

#### Description

App crashes when i select "Jekyll Post" as Type in new file dialog. 

#### Log
```
FATAL EXCEPTION: main
Process: net.gsantner.markor, PID: 12503
java.lang.IllegalArgumentException: Unknown pattern character 'Y'
       at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
       at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:305)
       at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
       at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:258)
       at net.gsantner.markor.ui.NewFileDialog$1.onItemSelected(NewFileDialog.java:93)
       at android.widget.AdapterView.fireOnSelected(AdapterView.java:1165)
       at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:1154)
       at android.widget.AdapterView.access$300(AdapterView.java:59)
       at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:1121)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)       
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by gsantner** [comment]
thx for reporting, have already seen that on other report. trying to reproduce that on my devices.

**Comment by gsantner** [comment]
yeah it shold be `yyyy-MM-dd`.
