### ISSUE TITLE
Crashes when trying to open file on SD card / external storage

### ISSUE THREAD

**Issue by vertigo220** [gsantner/markor#816]
#### General information

* **App version: Latest, Google Play store
* **System: Android 8.0, Moto Z Play, stock

#### Description

Whenever I try opening a file on the SD card, whether from a file explorer app or directly through Markor, it crashes. Files on internal storage open fine. When browsing in Markor, the SD card and all folders/files on it have a line through them. I thought maybe it's an issue with it not having the rights granted to it, but it should still at least be able to read, just not write. It was working before, and the only thing I can think that might have caused the issue is that my SD card was going bad so I swapped it out, so Markor doesn't have permissions to the new card; however, I looked through settings and couldn't find an option to grant the necessary permissions, and if that is indeed the problem then it should state that, not just crash. I've submitted multiple crash reports when it happened.

#### Log

```[01-05 04:10:41.721 3245:3245 D/KP2AAF]
event: 32, package = net.gsantner.markor

[01-05 04:10:41.766 3245:3245 D/KP2AAF]
URL=androidapp://net.gsantner.markor

[01-05 04:10:41.792 3245:3245 D/KP2AAF]
event: 2048, package = net.gsantner.markor

[01-05 04:10:41.799 3245:3245 D/KP2AAF]
URL=androidapp://net.gsantner.markor

[01-05 04:10:41.827 3245:3245 D/KP2AAF]
event: 32, package = net.gsantner.markor

[01-05 04:10:41.843 3245:3245 D/KP2AAF]
URL=androidapp://net.gsantner.markor

[01-05 04:10:41.844 3245:3245 D/KP2AAF]
event: 2048, package = net.gsantner.markor

[01-05 04:10:41.866 3245:3245 D/KP2AAF]
URL=androidapp://net.gsantner.markor

[01-05 04:10:41.867 3245:3245 D/KP2AAF]
event: 2048, package = net.gsantner.markor

[01-05 04:10:41.875 3245:3245 D/KP2AAF]
URL=androidapp://net.gsantner.markor

[01-05 04:10:41.879 3245:3245 D/KP2AAF]
event: 2048, package = net.gsantner.markor

[01-05 04:10:41.887 3245:3245 D/KP2AAF]
URL=androidapp://net.gsantner.markor

[01-05 04:10:41.900 3245:3245 D/KP2AAF]
event: 2048, package = net.gsantner.markor

[01-05 04:10:41.912 3245:3245 D/KP2AAF]
URL=androidapp://net.gsantner.markor

[01-05 04:10:41.914 3245:3245 D/KP2AAF]
event: 2048, package = net.gsantner.markor

[01-05 04:10:41.921 3245:3245 D/KP2AAF]
URL=androidapp://net.gsantner.markor

[01-05 04:10:41.925 3245:3245 D/KP2AAF]
event: 2048, package = net.gsantner.markor

[01-05 04:10:41.933 3245:3245 D/KP2AAF]
URL=androidapp://net.gsantner.markor

[01-05 04:10:41.936 3245:3245 D/KP2AAF]
event: 2048, package = net.gsantner.markor

[01-05 04:10:41.944 3245:3245 D/KP2AAF]
URL=androidapp://net.gsantner.markor

[01-05 04:10:41.946 3245:3245 D/KP2AAF]
event: 2048, package = net.gsantner.markor

[01-05 04:10:41.953 3245:3245 D/KP2AAF]
URL=androidapp://net.gsantner.markor

[01-05 04:10:41.955 3245:3245 D/KP2AAF]
event: 2048, package = net.gsantner.markor

[01-05 04:10:41.962 3245:3245 D/KP2AAF]
URL=androidapp://net.gsantner.markor

[01-05 04:10:41.964 3245:3245 D/KP2AAF]
event: 2048, package = net.gsantner.markor

[01-05 04:10:41.970 3245:3245 D/KP2AAF]
URL=androidapp://net.gsantner.markor

[01-05 04:10:42.770 1738:2026 I/ActivityManager]
START u0 {flg=0x8080000 cmp=net.gsantner.markor/.activity.DocumentActivity (has extras)} from uid 10833

[01-05 04:10:42.786 633:633 D/SFPerfTracer]
       layers: (7:21) (StatusBar#0 (0xac345000): 0:53209) (com.android.systemui.ImageWallpaper#0 (0xac012000): 0:2806)* (#1 (0xac334000): 0:23242) (DimLayerController/Stack=0#0 (0xac092000): 0:3053)* (animation background stackId=1#0 (0xac063000): 0:346)* (Sprite#0 (0xac069000): 0:63)* (NavigationBar#0 (0xac1d5000): 5:10422) (#0 (0xac33c000): 0:325) (#4 (0xac07e000): 0:96) (#5 (0xac24b000): 0:55) (net.gsantner.markor/net.gsantner.markor.activity.MainActivity#0 (0xac562000): 0:161)- (com.android.systemui/com.android.systemui.recents.RecentsActivity#0 (0xac134000): 0:12)- (thumbnail anim#0 (0xac032000): 0:10)- (SnapshotStartingWindow for taskId=24046#0 (0xac25b000): 0:19)- (thumbnail anim#1 (0xac262000): 0:20)- (com.dp.logcatapp/com.dp.logcatapp.activities.MainActivity#0 (0xac032000): 0:43)- (com.android.systemui/com.android.systemui.recents.RecentsActivity#0 (0xac134000): 0:9)- (thumbnail anim#0 (0xac562000): 0:10)- (SnapshotStartingWindow for taskId=24034#0 (0xac250000): 0:20)- (thumbnail anim#1

[01-05 04:10:42.920 31496:31496 W/DocumentsContract]
Failed to create document
android.os.ParcelableException: java.io.FileNotFoundException: No root for 46464333-2d45-3239-3100-000000040000
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:80)
	at android.os.Parcel.readParcelable(Parcel.java:2782)
	at android.os.Parcel.readException(Parcel.java:1938)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
	at android.content.ContentProviderClient.call(ContentProviderClient.java:483)
	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1154)
	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1136)
	at android.support.v4.provider.TreeDocumentFile.createFile(TreeDocumentFile.java:53)
	at android.support.v4.provider.TreeDocumentFile.createDirectory(TreeDocumentFile.java:63)
	at net.gsantner.opoc.util.ShareUtil.getDocumentFile(ShareUtil.java:1095)
	at net.gsantner.opoc.util.ShareUtil.canWriteFile(ShareUtil.java:1039)
	at net.gsantner.markor.activity.DocumentEditFragment.onResume(DocumentEditFragment.java:197)
	at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
	at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
	at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
	at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
	at android.app.Activity.performResume(Activity.java:7112)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3641)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3706)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2915)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1606)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
Caused by: java.io.FileNotFoundException: No root for 46464333-2d45-3239-3100-000000040000
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
	... 37 more

[01-05 04:10:42.922 31496:31496 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: net.gsantner.markor, PID: 31496
java.lang.RuntimeException: Unable to resume activity {net.gsantner.markor/net.gsantner.markor.activity.DocumentActivity}: java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3666)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3706)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2915)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1606)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
Caused by: java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
	at net.gsantner.opoc.util.ShareUtil.getDocumentFile(ShareUtil.java:1093)
	at net.gsantner.opoc.util.ShareUtil.canWriteFile(ShareUtil.java:1039)
	at net.gsantner.markor.activity.DocumentEditFragment.onResume(DocumentEditFragment.java:197)
	at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
	at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
	at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
	at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
	at android.app.Activity.performResume(Activity.java:7112)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3641)
	... 10 more

[01-05 04:10:42.928 1738:2687 W/ActivityManager]
  Force finishing activity net.gsantner.markor/.activity.DocumentActivity

[01-05 04:10:42.930 1738:2687 W/ActivityManager]
  Force finishing activity net.gsantner.markor/.activity.MainActivity

[01-05 04:10:42.934 1738:1906 I/ActivityManager]
Showing crash dialog for package net.gsantner.markor u0

[01-05 04:10:43.430 1738:1905 W/ActivityManager]
Activity pause timeout for ActivityRecord{fe4239e u0 net.gsantner.markor/.activity.DocumentActivity t24047 f}

[01-05 04:10:44.027 1738:2687 W/ActivityManager]
  Force finishing activity net.gsantner.markor/.activity.DocumentActivity

[01-05 04:10:44.079 1738:2687 W/ActivityManager]
  Force finishing activity net.gsantner.markor/.activity.MainActivity

[01-05 04:10:44.084 1738:2687 I/ActivityManager]
Killing 31496:net.gsantner.markor/u0a833 (adj 900): crash

[01-05 04:10:44.789 633:633 D/SFPerfTracer]
       layers: (9:14) (StatusBar#0 (0xac345000): 0:53211) (com.android.systemui.ImageWallpaper#0 (0xac012000): 0:2807) (#1 (0xac334000): 0:23242) (DimLayerController/Stack=0#0 (0xac092000): 0:3075)* (animation background stackId=1#0 (0xac063000): 0:346)* (Sprite#0 (0xac069000): 0:63)* (NavigationBar#0 (0xac1d5000): 7:10437) (#0 (0xac33c000): 0:325) (#4 (0xac07e000): 0:96) (#5 (0xac24b000): 0:55) (net.gsantner.markor/net.gsantner.markor.activity.MainActivity#0 (0xac032000): 0:45)- (Application Error: net.gsantner.markor#0 (0xac134000): 0:25)- (com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher#0 (0xac562000): 7:17) (com.android.systemui/com.android.systemui.recents.RecentsActivity#0 (0xac134000): 7:10) ```
<!-- 
  Look for already reported issues before posting!
  Also take a look at documentation and wiki, or write in the project chat.

  App version: The version of the app installed and the installation source. Example: v0.3.5 F-Droid
               Please keep in mind that only the latest downloadable version is supported and that there are no backports to older versions.
  System:      Information about where the app is running. Give all details you know, but at least the Android OS version.
               Example: Android 8.0.1, Nexus 5, LineageOS

  Description:
  What this is about, what happens and what is expected to happen. What needs to be done for it to happen.
  If a crash is happening a log is needed. Screenshots or demonstration videos are always helpful too.

  About logging:
  https://gsantner.net/blog/2018/03/19/android-contribution-guide.html?packageid=net.gsantner.markor&project=markor&web=https://github.com/gsantner/markor#logcat
-->

**Comment by gsantner** [comment]
is this new with a recent update?
whats your Markor version?

**Comment by gsantner** [comment]
closing as no response.
